CREATE DATABASE VENDA

CREATE TABLE MARCELO
	(
	ID INT PRIMARY KEY,
	IDADE INT NOT NULL UNIQUE,
	CIDADE VARCHAR (MAX) NULL,
	)

	ALTER TABLE MARCELO ADD UF CHAR (2) NULL
	ALTER TABLE MARCELO ADD TELEFONE NUMERIC NOT NULL