CREATE DATABASE VENDA

CREATE TABLE MARCELO
	(
	ID INT PRIMARY KEY,
	IDADE INT NOT NULL UNIQUE,
	CIDADE VARCHAR (MAX) NULL,
	)

	ALTER TABLE MARCELO ADD UF CHAR (2) NULL
	ALTER TABLE MARCELO ADD TELEFONE NUMERIC NOT NULL

	DROP TABLE MARCELO

CREATE TABLE VEICULO
	(
	Id INT PRIMARY KEY,
	Descricao VARCHAR (100) NOT NULL,
	DataCriacao DATETIME NOT NULL,
	TipoMotor DECIMAL NOT NULL,
	Vendo BIT NOT NULL,
	)

CREATE TABLE COR
	(
	Id INT PRIMARY KEY,
	NomeCor VARCHAR (100) NOT NULL UNIQUE,
	)

ALTER TABLE COR ADD "IdCOR" INT;
ALTER TABLE COR ADD CONSTRAINT fk_VEICULO_COR FOREIGN KEY ("IdCOR") REFERENCES VEICULO(id);